### ISSUE TITLE
Cannot stop the application

### ISSUE THREAD

**Issue by jordensy** [cescoffier/quarkus-langchain4j-workshop#30]
When I toggle the live reload "l" so it is disabled and then hit "q" I still get a live reload. no matter what I try it keeps reloading. forcing an error during build by pressing different ctrl+ key allows me to stop the application by hitting "q"

Am I doing something wrong or miss-out on some things?

I use the quarkus platform BOM 3.15.1
Quarkus Lanchain4j 0.20

**Comment by cescoffier** [comment]
Which OS / terminal are you using? And which step are you in?

**Comment by jordensy** [comment]
> Which OS / terminal are you using? And which step are you in?

Windows 11, InteliJ 2024.1.2

**Comment by jordensy** [comment]
It seems that the commands are working fine in a windows terminal. I just found out that I only have these issues when ussing the commands from an InteiJ terminal

**Comment by geoand** [comment]
That sounds like a bug in the IntelliJ terminal

**Comment by jordensy** [comment]
Must be InteliJ issue
